### ISSUE TITLE
Content Suggestion: Last paragraph

### ISSUE THREAD

**Issue by myersj451** [Nikki-Luoma/about-me#4]
Under 0fa1f5c4125abb87791dd18a899c8d7b07f929dc , 
The bio could become stronger if you can connect the importance of technology in your life to your dream of travelling the world and/or helping people.
Ex: could developing new technology aid developing countries you travel to? 

Also, adding more information about how you raised $5,000 and what you did with the money could provide a better understanding of your work.

**Comment by Nikki-Luoma** [comment]
Thank you. I knew I needed more information but was unsure how.
