### ISSUE TITLE
Suggestion about Transition

### ISSUE THREAD

**Issue by liux2** [Nikki-Luoma/about-me#5]
In this assignment, we have to combine the theme with paragraphs. I remembered that the professor said we could add some software connected sentences to be our natural transition sentences. It would be good if you add something like that. 

ps. Sorry, you gave me a lot of suggestions, but I can only give you this suggestion. I'm not good at grammars. sorry....

**Comment by Nikki-Luoma** [comment]
Thank you for your feedback, I added transitions.
